using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Database.Implementations;
using Jellyfin.Plugin.JFLint.Models;
using MediaBrowser.Common.Api;
using MediaBrowser.Controller;
using MediaBrowser.Controller.Dto;
using MediaBrowser.Controller.Entities;
using MediaBrowser.Controller.Library;
using MediaBrowser.Controller.Persistence;
using MediaBrowser.Model.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Jellyfin.Plugin.JFLint.Controllers;

/// <summary>
/// Findings about the rows that describe an item's images.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why the row count needs a route, stated narrowly because the broad version is false.</b>
/// In <b>bulk</b>, Jellyfin reports an image once however many rows describe it:
/// <c>BaseItemDto.ImageTags</c> is a <c>Dictionary&lt;ImageType, string&gt;</c> and holds one
/// entry per type by construction, so a row that exists 65,536 times looks exactly like one
/// that exists once. <b>Per item it is not hidden at all</b> -
/// <c>GET /Items/{id}/Images</c> walks <c>item.ImageInfos</c> and emits one entry per entry,
/// in both of its passes, so duplicates do show up there. The gap this route fills is
/// therefore the same one <c>MediaInfoDB</c> fills: not "the server cannot answer", but "the
/// server can only be asked one item at a time", and one call per item is 164,000 calls on the
/// reference library. A first draft of this comment claimed HTTP could not answer it at all;
/// that was a negative claim about every route, drawn from the one that happened to be looked
/// at, and reading <c>ImageController</c> refuted it.
/// </para>
/// <para>
/// The scale is not hypothetical:
/// jellyfin/jellyfin#17192 carries the reporter's own words - <i>"I have one movie with 262,144
/// image rows in my DB with 4 real images"</i> and <i>"If I clean them up manually the library
/// scan becomes fast again"</i> - read in the issue rather than taken second hand.
/// </para>
/// <para>
/// <b>What that issue's analysis gets wrong, measured here, because it would otherwise be read
/// as a reason to distrust this route's other half.</b> The write-up in it names three factors,
/// and the first is "duplicate materialization on read": that
/// <c>PrepareItemQuery</c>'s <c>AsNoTracking()</c> plus <c>AsSingleQuery()</c> plus several
/// collection <c>Include</c>s hands back <c>|Images| x |other collections|</c> copies. <b>That
/// does not reproduce.</b> With all four collections included the join really does return 24
/// rows for 2 images - checked with raw SQL so the control fires - and EF still materialises
/// exactly 2, on EF Core 9.0.0, 9.0.11 and 10.0.11. The write-up is flagged as AI-generated by
/// its own author, who also says it was never run.
/// </para>
/// <para>
/// The other two factors are untouched by that: a save deletes and re-inserts an item's rows
/// without deduplicating, and the table's primary key is a fresh <c>Guid</c> per row so
/// duplicate inserts never collide. Those explain why duplicates <b>persist</b> once they
/// exist. Where they come from is unsettled, and this route does not need to know - it reports
/// the rows either way.
/// </para>
/// <para>
/// <b>What the pair is worth here, which is more than transport.</b> The database half reads the
/// raw <c>Path</c> column and the object-model half reads the materialised property, and those
/// two are not the same string: an image path is written through <c>GetPathToSave</c> and read
/// back through <c>appHost.ExpandVirtualPath</c> (10.11 <c>BaseItemRepository.Map</c>, v12
/// <c>BaseItemMapper.MapImageFromEntity</c>). For media that substitution is a corner case; for
/// images it is the common case, because downloaded artwork lives under the metadata directory.
/// That is exactly where this plugin's one released path defect lived, and it is why this route
/// got a twin rather than following <c>MediaInfoDB</c>.
/// </para>
/// <para>
/// <b>And the twin is possible, which had to be established rather than assumed.</b>
/// <c>MediaInfoDB</c> has no twin because <c>MediaStreamQuery.ItemId</c> is a non-nullable
/// <c>Guid</c>, so streams can only be fetched one item at a time. Images have no such limit,
/// and nothing on the read path folds duplicate rows: <c>InternalItemsQuery</c> defaults
/// <c>DtoOptions.EnableImages</c> to true, <c>PrepareItemQuery</c> adds
/// <c>Include(e =&gt; e.Images)</c>, and the mapper assigns
/// <c>entity.Images.Select(...).ToArray()</c> - a plain projection, with no <c>Distinct</c> and
/// no dictionary. Every row also carries its own primary key, so EF's identity resolution does
/// not collapse them either. <c>item.ImageInfos</c> therefore holds one entry per row.
/// </para>
/// <para>
/// <b>Both halves name every item kind, and that is a requirement rather than a narrowing.</b>
/// An unrestricted <c>GetItemList</c> dies on the first row whose <c>Type</c> no longer resolves
/// to a class - a leftover from a removed plugin - and the database half has to apply the same
/// list or it would report image rows belonging to items its twin can never return.
/// </para>
/// <para>
/// <b>A blind spot both halves share - and it is not empty, which was measured on the first
/// run.</b> A row is unreachable here when it belongs to no <c>BaseItems</c> row at all, or to
/// one whose <c>Type</c> is not in <c>BaseItemKindNames</c>: the database half inner-joins it
/// away, and the object-model half never materialises such an item to read images from. Both
/// halves drop the same rows, so the pair still agrees - agreement about a row neither half can
/// see is not evidence about it.
/// </para>
/// <para>
/// On the reference library that blind spot holds <b>6 rows</b>: 75 rows carry no blurhash and
/// 70 are reported, 1 row has no dimensions and 0 are reported. The grouping does not account
/// for it - <c>SUM(RowCount)</c> comes to 70, not 75, and the one duplicated image is a
/// person's poster unrelated to the others. Which of the two causes it is has not been
/// established at the time of writing; the query that separates them is a <c>LEFT JOIN</c> onto
/// <c>BaseItems</c> grouped by <c>Type</c>, where a null type means an orphan and a real one
/// means an item kind this plugin deliberately does not name.
/// </para>
/// <para>
/// Widening the type list is not the fix, and that is the reason this stays a documented limit
/// rather than a defect: an unrestricted <c>GetItemList</c> dies on the first unknown type, on
/// this very server. The honest position is that the route reports what both halves can see,
/// and says here how much it cannot.
/// </para>
/// <para>
/// Requires elevation, like everything else here, because the responses carry file paths.
/// </para>
/// </remarks>
/// <param name="libraryManager">Instance of the <see cref="ILibraryManager"/> interface.</param>
/// <param name="itemTypeLookup">Instance of the <see cref="IItemTypeLookup"/> interface.</param>
/// <param name="appHost">Instance of the <see cref="IServerApplicationHost"/> interface, used to
/// expand the stored form of a path - see <see cref="StoredPath"/>.</param>
/// <param name="dbContextFactory">Factory for the Jellyfin database context.</param>
[ApiController]
[Route("JFLint")]
[Authorize(Policy = Policies.RequiresElevation)]
[Produces(MediaTypeNames.Application.Json)]
public class ImageInfoController(
    ILibraryManager libraryManager,
    IItemTypeLookup itemTypeLookup,
    IServerApplicationHost appHost,
    IDbContextFactory<JellyfinDbContext> dbContextFactory) : ControllerBase
{
    /// <summary>
    /// Gets image-row findings through <see cref="ILibraryManager"/>.
    /// </summary>
    /// <remarks>
    /// The slow half of the pair, and slow for a structural reason rather than a fixable one: it
    /// materialises every item in the library so that it can read the images each one carries.
    /// A caller should ask <c>ImageInfoDB</c> first and fall back to this one.
    /// </remarks>
    /// <response code="200">Findings returned.</response>
    /// <returns>One row per image and check, not per database row.</returns>
    [HttpGet("ImageInfo")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public ActionResult<IReadOnlyList<ImageRowFindingDto>> GetImageFindings()
    {
        var shortNames = ShortTypeNames();
        var findings = new List<ImageRowFindingDto>();

        foreach (var item in libraryManager.GetItemList(new InternalItemsQuery
        {
            IncludeItemTypes = itemTypeLookup.BaseItemKindNames.Keys.ToArray(),
            Recursive = true,

            // Asking for images and nothing else, and the reason is cost rather than
            // correctness - which matters, because a later reader who removes this line should
            // know what they are and are not breaking. A default DtoOptions carries every
            // ItemField and EnableUserData, so ApplyNavigations adds four collection Includes
            // to one AsSingleQuery: the join then returns |images| x |userdata| x |providers| x
            // |lockedFields| rows per item. Measured on a seeded model, that is 24 rows to
            // deliver 2 images - across this library, on a spinning disk, for a route that is
            // already the slow half.
            //
            // It is NOT what keeps the answer right. The obvious fear - that the cartesian
            // inflates item.ImageInfos and this route would invent duplicates - was measured
            // rather than assumed, and it does not happen: with all four Includes the join
            // really does return 24 rows (checked with raw SQL, so the control fires) and EF
            // still materialises 2 images, on EF Core 9.0.0, 9.0.11 and 10.0.11 alike. The
            // materialiser folds repeats of a key, and genuine duplicate rows survive it
            // because each carries its own Guid.NewGuid() primary key - which is exactly the
            // property this route depends on.
            DtoOptions = new DtoOptions(false) { EnableUserData = false }
        }))
        {
            var images = item.ImageInfos;
            if (images is null || images.Length == 0)
            {
                continue;
            }

            var itemType = ShortTypeNameOf(item, shortNames);

            // Grouped by the same key the database half groups by, so the two produce the same
            // rows. Not by row: the object model cannot see a row's primary key - the mapper
            // drops it - so two findings about two identical rows would tie on every field and
            // the halves could agree on the set while differing in order.
            foreach (var group in images.GroupBy(image => new { image.Type, image.Path }))
            {
                var rows = group.ToList();
                var imageType = group.Key.Type.ToString();

                if (rows.Count > 1)
                {
                    findings.Add(new ImageRowFindingDto(
                        item.Id,
                        item.Name,
                        itemType,
                        imageType,
                        group.Key.Path,
                        rows.Count,
                        ImageFindingKind.ImageRowDuplicated));
                }

                var withoutDimensions = rows.Count(row => row.Width == 0 || row.Height == 0);
                if (withoutDimensions > 0)
                {
                    findings.Add(new ImageRowFindingDto(
                        item.Id,
                        item.Name,
                        itemType,
                        imageType,
                        group.Key.Path,
                        withoutDimensions,
                        ImageFindingKind.ImageWithoutDimensions));
                }

                // IsNullOrEmpty, because the column is a blob and the mapper decodes it with
                // Encoding.UTF8.GetString: a zero-length blob arrives here as "" and not as
                // null. The database half asks length(Blurhash) = 0 for the same reason.
                var withoutBlurhash = rows.Count(row => string.IsNullOrEmpty(row.BlurHash));
                if (withoutBlurhash > 0)
                {
                    findings.Add(new ImageRowFindingDto(
                        item.Id,
                        item.Name,
                        itemType,
                        imageType,
                        group.Key.Path,
                        withoutBlurhash,
                        ImageFindingKind.ImageWithoutBlurhash));
                }
            }
        }

        return Ok(Sorted(findings));
    }

    /// <summary>
    /// Gets image-row findings straight from the database.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token supplied by the framework.</param>
    /// <response code="200">Findings returned.</response>
    /// <returns>One row per image and check.</returns>
    /// <remarks>
    /// <para>
    /// Three narrow queries rather than one pass over the table: on the reference library the
    /// table holds about 130,000 rows and the findings are a handful, so every predicate is
    /// answered in SQL and only matching rows leave the database.
    /// </para>
    /// <para>
    /// <b>Every shape here was checked for translation on both EF Core lines before it was
    /// written, and that is not ceremony.</b> A previous release of this plugin used
    /// <c>Contains('.')</c>, which compiled clean, translated on EF Core 10 and threw at query
    /// time on the whole EF Core 9 line that Jellyfin 10.11 ships - it would have shipped green
    /// and answered 500 on the server it was built for. The grouped count, the join onto the
    /// grouped result and the blurhash length test were each generated and executed against
    /// SQLite on EF Core 9.0.11 and 10.0.11, with <c>Contains(char)</c> in the same run as the
    /// negative control: it fails on 9 and succeeds on 10, so the green results are not a blind
    /// instrument.
    /// </para>
    /// <para>
    /// The grouping runs on the <b>stored</b> spelling of the path and the result is expanded
    /// afterwards, because grouping is what the query is for. Two stored paths that expand to
    /// one string would therefore be reported as two findings where the object-model half sees
    /// one - which needs a real path to contain a literal <c>%MetadataPath%</c>, and is recorded
    /// here rather than guarded against.
    /// </para>
    /// </remarks>
    [HttpGet("ImageInfoDB")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<ActionResult<IReadOnlyList<ImageRowFindingDto>>> GetImageFindingsFromDatabaseAsync(
        CancellationToken cancellationToken)
    {
        var wantedTypes = itemTypeLookup.BaseItemKindNames.Values.ToArray();
        var shortNames = ShortTypeNames();

        var dbContext = await dbContextFactory.CreateDbContextAsync(cancellationToken).ConfigureAwait(false);
        await using (dbContext.ConfigureAwait(false))
        {
            // The same restriction the object-model half applies through IncludeItemTypes. An
            // image row hanging off an item whose type no longer resolves would otherwise be
            // reported by this half alone.
            var items = dbContext.BaseItems.AsNoTracking().Where(item => wantedTypes.Contains(item.Type));

            var duplicated = await Grouped(dbContext.BaseItemImageInfos.AsNoTracking(), items)
                .Where(row => row.RowCount > 1)
                .ToListAsync(cancellationToken)
                .ConfigureAwait(false);

            var withoutDimensions = await Grouped(
                    dbContext.BaseItemImageInfos.AsNoTracking().Where(image => image.Width == 0 || image.Height == 0),
                    items)
                .ToListAsync(cancellationToken)
                .ConfigureAwait(false);

            // length(Blurhash) = 0, never Blurhash = ''. The column is a blob, and in SQLite a
            // blob never compares equal to a text value - so "= ''" cannot match even an empty
            // blob, silently. Measured on sqlite 3.46.1 with the control that the same
            // comparison against a text column does match.
            var withoutBlurhash = await Grouped(
                    dbContext.BaseItemImageInfos.AsNoTracking().Where(image => image.Blurhash == null || image.Blurhash.Length == 0),
                    items)
                .ToListAsync(cancellationToken)
                .ConfigureAwait(false);

            var findings = new List<ImageRowFindingDto>();
            findings.AddRange(duplicated.Select(row => Map(row, shortNames, ImageFindingKind.ImageRowDuplicated)));
            findings.AddRange(withoutDimensions.Select(row => Map(row, shortNames, ImageFindingKind.ImageWithoutDimensions)));
            findings.AddRange(withoutBlurhash.Select(row => Map(row, shortNames, ImageFindingKind.ImageWithoutBlurhash)));

            return Ok(Sorted(findings));
        }
    }

    /// <summary>
    /// Collapses image rows to one row per image and joins the owning item onto it.
    /// </summary>
    /// <param name="images">The image rows to consider, already narrowed by the caller.</param>
    /// <param name="items">The items the rows may belong to, already narrowed to known kinds.</param>
    /// <returns>One row per item, image type and stored path, carrying how many rows it covers.</returns>
    /// <remarks>
    /// One shared shape for all three checks rather than three written out, so the grouping key
    /// cannot drift between them - the three have to agree on what "one image" means or their
    /// row counts are not comparable with each other.
    /// </remarks>
    private static IQueryable<ImageGroupRow> Grouped(
        IQueryable<Jellyfin.Database.Implementations.Entities.BaseItemImageInfo> images,
        IQueryable<Jellyfin.Database.Implementations.Entities.BaseItemEntity> items)
        => images
            .GroupBy(image => new { image.ItemId, image.ImageType, image.Path })
            .Select(group => new
            {
                group.Key.ItemId,
                group.Key.ImageType,
                group.Key.Path,
                RowCount = group.Count()
            })
            .Join(
                items,
                group => group.ItemId,
                item => item.Id,
                (group, item) => new ImageGroupRow
                {
                    ItemId = group.ItemId,
                    ItemName = item.Name,
                    StoredType = item.Type,
                    ImageType = group.ImageType,
                    StoredPath = group.Path,
                    RowCount = group.RowCount
                });

    /// <summary>
    /// Turns one grouped database row into a finding.
    /// </summary>
    /// <param name="row">The grouped row.</param>
    /// <param name="shortNames">Fully qualified type name to short name.</param>
    /// <param name="kind">Which check produced it.</param>
    /// <returns>The finding.</returns>
    private ImageRowFindingDto Map(ImageGroupRow row, Dictionary<string, string> shortNames, string kind)
        => new(
            row.ItemId,
            row.ItemName,
            row.StoredType is not null && shortNames.TryGetValue(row.StoredType, out var name) ? name : row.StoredType ?? string.Empty,

            // Cast to MediaBrowser.Model.Entities.ImageType before naming it, which is the cast
            // Jellyfin itself applies when it materialises the row. The two halves then spell
            // the image type identically by construction rather than by the two enums happening
            // to carry the same member names.
            ((ImageType)row.ImageType).ToString(),
            StoredPath.Expand(appHost, row.StoredPath),
            row.RowCount,
            kind);

    /// <summary>
    /// Inverts <see cref="IItemTypeLookup.BaseItemKindNames"/> so a stored fully qualified type
    /// name can be reported as its short name.
    /// </summary>
    /// <returns>Fully qualified type name to short name.</returns>
    private Dictionary<string, string> ShortTypeNames()
    {
        var names = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var pair in itemTypeLookup.BaseItemKindNames)
        {
            names[pair.Value] = pair.Key.ToString();
        }

        return names;
    }

    /// <summary>
    /// Names a materialised item's type from the same table the database half reads.
    /// </summary>
    /// <param name="item">The item.</param>
    /// <param name="shortNames">Fully qualified type name to short name.</param>
    /// <returns>The short type name.</returns>
    /// <remarks>
    /// Not <c>GetBaseItemKind()</c>, which parses the client-facing name and has already been
    /// measured to disagree with the lookup - it answered <c>ManualPlaylistsFolder</c> where the
    /// twin said <c>PlaylistsFolder</c> for one and the same row.
    /// </remarks>
    private static string ShortTypeNameOf(BaseItem item, Dictionary<string, string> shortNames)
    {
        var typeName = item.GetType().FullName;
        return typeName is not null && shortNames.TryGetValue(typeName, out var name)
            ? name
            : item.GetBaseItemKind().ToString();
    }

    /// <summary>
    /// Orders findings the same way on both halves, so the pair can be read line by line.
    /// </summary>
    /// <param name="findings">The findings to order.</param>
    /// <returns>The findings by kind, item, image type and path.</returns>
    /// <remarks>
    /// <c>Kind</c> leads because a caller groups by it. The four keys together are unique by
    /// construction - one finding per kind per image - which is the whole reason the findings
    /// are grouped rather than emitted per row; there is no row id left to break a tie with.
    /// </remarks>
    private static List<ImageRowFindingDto> Sorted(IEnumerable<ImageRowFindingDto> findings)
        => findings
            .OrderBy(finding => finding.Kind, StringComparer.Ordinal)
            .ThenBy(finding => finding.ItemName is null)
            .ThenBy(finding => finding.ItemName, StringComparer.Ordinal)
            .ThenBy(finding => finding.ItemId)
            .ThenBy(finding => finding.ImageType, StringComparer.Ordinal)
            .ThenBy(finding => finding.Path, StringComparer.Ordinal)
            .ToList();

    /// <summary>
    /// One grouped image row with its owning item, before the path is expanded and the types
    /// are named.
    /// </summary>
    /// <remarks>
    /// A named type rather than an anonymous one because <see cref="Grouped"/> returns it to a
    /// caller; an anonymous type cannot be written as a return type.
    /// </remarks>
    private sealed class ImageGroupRow
    {
        /// <summary>Gets or sets the owning item's id.</summary>
        public Guid ItemId { get; set; }

        /// <summary>Gets or sets the owning item's name.</summary>
        public string? ItemName { get; set; }

        /// <summary>Gets or sets the owning item's stored, fully qualified type name.</summary>
        public string? StoredType { get; set; }

        /// <summary>Gets or sets the image type as the column holds it.</summary>
        public Jellyfin.Database.Implementations.Entities.ImageInfoImageType ImageType { get; set; }

        /// <summary>Gets or sets the path in the spelling the column holds.</summary>
        public string? StoredPath { get; set; }

        /// <summary>Gets or sets how many rows this finding covers.</summary>
        public int RowCount { get; set; }
    }
}
